### ISSUE TITLE
Visual Studio 2015 doesn't compile testlib.h 0.9.10

### ISSUE THREAD

**Issue by helgui** [MikeMirzayanov/testlib#54]
Compilation fails on line 426
`_setmode(_fileno(file), O_BINARY);`
with error:
...\testlib\testlib.h(426): error C2039: _file: is not a member of  '_iobuf'

If I comment lines
`#ifndef _fileno`
`#define _fileno(_stream)  ((_stream)->_file)`
`#endif`
error disappears because `_fileno` from `<stdio.h>` is a function but not a macro. Now there is another error:
...\Microsoft Visual Studio 14.0\VC\include\vadefs.h(145): error C2338: va_start argument must not have reference type and must not be parenthesized
...\testlib\testlib.h(313): note: see reference to class template instantiation 'void __vcrt_va_start_verify_argument_type<const std::string&>(void) throw()' being compiled

313-th line:
`FMT_TO_RESULT(fmt, fmt.c_str(), result);`

Visual studio version:
Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1

**Comment by alikhil** [comment]
@helgui To fix second error use `#define _CRT_NO_VA_START_VALIDATION` in your code

**Comment by MikeMirzayanov** [comment]
Done in 0.9.12.

**Comment by slycelote** [comment]
@MikeMirzayanov I still see the same error ("C2039: _file: is not a member of '_iobuf'") in VS 2015 and 2017.

**Comment by andgein** [comment]
Confirm. I see this error in VS 2017. Testlib version is 0.9.12
